string map_name
---
bool success
string message
string map_pgm_path
string map_yaml_path
---
string state
uint32 cells_known
float32 coverage_percent
float32 elapsed_sec
float32 resolution
uint32 width
uint32 height
